config/routes.rb
Rails.application.routes.draw do

  mount API => '/'
  
  resources :documents, only: [:index, :new, :create, :destroy]   
  root 'documents#home'

  get 'documents/download_pdf'
  get 'documents/download'
  get 'documents/display'

end

app/models/document.rb
class Document < ActiveRecord::Base
	mount_uploader :attachment, AttachmentUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery prepend: true
end

app/controllers/documents_controller.rb
require 'prawn'
require 'yomu'

class DocumentsController < ApplicationController
  def home 
    @document = Document.new
  end

  def index
    @documents = Document.all
  end

  def create
  	@document = Document.new(document_params)
    if @document.save
      yomu = Yomu.new "#{@document.attachment.current_path}"

      if File.extname("#{@document.attachment_identifier}") == '.pdf'
        @document.content = yomu.text
        @document.save
        redirect_to action: 'display'
      else 
        Prawn::Document.generate('test.pdf') do
          font_families.update("Lato" => {
          :normal => Rails.root.join("app/assets/fonts/Lato-Regular.ttf"),
          :italic => Rails.root.join("app/assets/fonts/Lato-Regular.ttf"),
          :bold => Rails.root.join("app/assets/fonts/Lato-Regular.ttf"),
          :bold_italic => Rails.root.join("app/assets/fonts/Lato-Regular.ttf")
        })

        font "Lato"
        text yomu.text
        end

        redirect_to action: 'download'
      end
    end
  end

  def destroy
  	@document = Document.find(params[:id])
  	@document.destroy
  	redirect_to documents_path, notice: "Successfully deleted"
  end

  def download_pdf
    send_file("#{Rails.root}/test.pdf", filename: "test.pdf", type: "application/pdf", disposition: "attachment")
  end

  private   
      def document_params   
      params.require(:document).permit(:attachment, :content) 
   end 
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/create.html.erb
<h1>Converter</h1>

<div>
	<b>Create</b>
</div> 

app/views/documents/destroy.html.erb
<h1>Documents#destroy</h1>
<p>Find me in app/views/documents/destroy.html.erb</p>

app/views/documents/display.html.erb
<style type="text/css">
    a {text-decoration: none;}
    a:hover {text-decoration: none;}
</style>

<div class="container">
	<br><br>
	<h1><a href="/" style="color:black">Converter</a></h1>
	<br>
	<%= Document.all.last.content %>
</div> 

app/views/documents/download.html.erb
<style type="text/css">
    a {text-decoration: none;}
    a:hover {text-decoration: none;}
</style>

<div class="container">
	<br><br>
	<h1><a href="/" style="color:black">Converter</a></h1>
	<br>
	<%= link_to 'Download PDF', documents_download_pdf_url, data: {turbolinks: false} %>
</div> 

app/views/documents/home.html.erb
<style type="text/css">
    a {text-decoration: none;}
    a:hover {text-decoration: none;}
</style>

<div class="container">
	<br><br>
	<h1><a href="/" style="color:black">Converter</a></h1>
	<br>
	<b>Upload the file</b>
	<br>
	<%= form_for @document, html: { multipart: true } do |f| %>   
      <%= f.file_field :attachment %>
      <br>
      <%= f.submit "Submit" %>
    <% end %>
</div> 

app/views/documents/index.html.erb
<h1>Converter</h1>
<p>Find me in app/views/documents/index.html.erb</p>

app/views/documents/new.html.erb
<h1>Converter</h1>

<b>Upload the file</b>
<div>
	<%= form_for @document, html: { multipart: true } do |f| %>   
      <%= f.file_field :attachment %>
      <%= f.submit "Submit" %>
    <% end %>
</div> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Converter</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/template.html.erb
<HTML>
	<BODY>
		<p><%= @text %></p>
	</BODY>
</HTML>